### PR TITLE
Add welcome message & get involved section

### PR DESCRIPTION
**Pull request by eyermt**
Rough drafts of both, but iteration is key.

### CODE REVIEW

**Comment by eyermt** [comment]
We could establish code review protocol between maintainers at some point. This is mainly to get the feel for it.

**Review by cuppajoe123 — COMMENTED** [review]
Maybe the **How to participate** section should be combined into the **Get involved** section, since they are similar topics. The whole section could be called **Getting involved**.

**Comment by eyermt** [comment]
I appreciate having different sections with varying levels of commitment, so theres a progression to getting involved. I feel it makes taking the first step less daunting, and makes the order of operations more clear.

**Comment by cuppajoe123** [comment]
Okay, I can understand that. Should we then move the bullet point about the soon-to-be IRC channel to the more beginner friendly **Getting Involved** section?

Also, I think the welcome message is good :)

**Comment by eyermt** [comment]
Yeah, "IRC (coming soon)" in the get involved sounds great.

**Pull request merged**
